# Generated by Django 3.0.2 on 2020-01-10 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256)),
                ('date_composed', models.DateTimeField(auto_now=True, verbose_name='Date Composed')),
                ('date_sent', models.DateTimeField(verbose_name='Date Sent')),
                ('sent_to', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
    ]
