# Generated by Django 3.0.2 on 2020-01-27 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id_number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Identification Number')),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, default='0704893840', max_length=12, verbose_name='Phone Number')),
                ('voting_centre', models.CharField(default='Unity Primary School', max_length=50, verbose_name='Voting Centre')),
                ('uploaded_to_google', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(default='')),
                ('venue', models.CharField(max_length=150, verbose_name='Event Venue')),
                ('time', models.DateTimeField()),
                ('attendants_count', models.IntegerField(default=0, verbose_name='Number of Attendants')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('members', models.ManyToManyField(to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(primary_key=True, serialize=False)),
                ('surname', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('initiation_date', models.DateField(verbose_name='Initiation Date')),
                ('project_budget', models.IntegerField()),
                ('completion_date', models.DateField(verbose_name='Completion Date')),
                ('contractor', models.CharField(max_length=50, verbose_name='Contractor Name')),
                ('project_description', models.TextField(verbose_name='Project Description')),
                ('completion_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='SelfHelpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=150, verbose_name='Registration Number')),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, verbose_name='Mobile Phone Number')),
            ],
            options={
                'verbose_name': 'Self Help Group',
                'verbose_name_plural': 'Self Help Groups',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.IntegerField()),
                ('school', models.CharField(max_length=150)),
                ('form', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Person')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SponsoredStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Student')),
            ],
            options={
                'verbose_name': 'Sponsored Student',
                'verbose_name_plural': 'Sponsored Students',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('remarks', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Student')),
            ],
            options={
                'verbose_name': 'Results',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Nhif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispending', models.BooleanField(default=False, verbose_name='Pending Status')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'NHIF',
                'verbose_name_plural': 'NHIF',
            },
        ),
        migrations.CreateModel(
            name='NCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_status', models.BooleanField(default=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'National Contruction Authority',
                'verbose_name_plural': 'National Contruction Authority',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_sorted', models.BooleanField(default=False)),
                ('date_sorted', models.DateTimeField(default=datetime.datetime(2020, 1, 27, 18, 45, 59, 958152, tzinfo=utc))),
                ('type_of_isssue', models.CharField(choices=[('CT', 'Complaint'), ('CO', 'Concern'), ('OT', 'Others')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='GroupEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(default='')),
                ('venue', models.CharField(max_length=150, verbose_name='Event Venue')),
                ('time', models.DateTimeField()),
                ('attendants_count', models.IntegerField(default=0, verbose_name='Number of Attendants')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Group')),
            ],
            options={
                'verbose_name': 'Group Event',
                'verbose_name_plural': 'Group Events',
            },
        ),
        migrations.CreateModel(
            name='CuriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField()),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'Curiculum Vitae',
                'verbose_name_plural': 'Curiculum Vitaes',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=50)),
                ('college_location', models.CharField(max_length=50)),
                ('date_enrolled', models.DateField(verbose_name='Enrollement Date')),
                ('date_completed', models.DateField(verbose_name='Completion Date')),
                ('course', models.CharField(max_length=50)),
                ('duration', models.IntegerField(verbose_name='Period of Years')),
                ('is_dropout', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.AddField(
            model_name='citizen',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Person'),
        ),
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('bursary_id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_issued', models.DateField()),
                ('amount_awarded', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Student')),
            ],
            options={
                'verbose_name': 'Bursary',
                'verbose_name_plural': 'Bursarys',
            },
        ),
    ]
