# Generated by Django 3.0.2 on 2020-01-10 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 10, 6, 44, 508157, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_sorted', models.BooleanField(default=False)),
                ('date_sorted', models.DateTimeField(default=datetime.datetime(2020, 1, 10, 10, 6, 44, 509155, tzinfo=utc))),
                ('type_of_isssue', models.CharField(choices=[('CT', 'Complaint'), ('CO', 'Concern'), ('OT', 'Others')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
