# Generated by Django 3.0.2 on 2020-01-28 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20200127_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bursary',
            options={'verbose_name': 'Bursary', 'verbose_name_plural': 'Bursary'},
        ),
        migrations.AlterModelOptions(
            name='curiculumvitae',
            options={'verbose_name': 'Curiculum Vitae', 'verbose_name_plural': 'Curiculum Vitae'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='bursary',
            name='bursary_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Person'),
        ),
        migrations.AlterField(
            model_name='college',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen'),
        ),
        migrations.AlterField(
            model_name='college',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 28, 11, 3, 10, 771279, tzinfo=utc), verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='curiculumvitae',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 3, 10, 767282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nca',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen'),
        ),
        migrations.AlterField(
            model_name='nhif',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Person'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.Citizen'),
        ),
    ]
