# Generated by Django 3.0.2 on 2020-01-29 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_auto_20200128_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='form',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='college',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 29, 17, 30, 33, 418267, tzinfo=utc), verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 17, 30, 33, 414271, tzinfo=utc)),
        ),
    ]
