# Generated by Django 3.0.2 on 2020-01-11 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_auto_20200111_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 17, 55, 3, 471983, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 17, 55, 3, 472985, tzinfo=utc)),
        ),
    ]
