# Generated by Django 3.0.2 on 2020-01-30 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20200129_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_sponsored',
            field=models.BooleanField(default=False, verbose_name='Sponsored Students'),
        ),
        migrations.AlterField(
            model_name='college',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 30, 6, 37, 55, 879931, tzinfo=utc), verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 6, 37, 55, 875934, tzinfo=utc)),
        ),
    ]
