# Generated by Django 3.0.2 on 2020-01-14 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20200111_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 9, 35, 33, 224851, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='surname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='citizens.Citizen'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 9, 35, 33, 225851, tzinfo=utc)),
        ),
    ]
