# Generated by Django 3.0.2 on 2020-01-31 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20200130_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterField(
            model_name='college',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 31, 10, 5, 36, 586784, tzinfo=utc), verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 10, 5, 36, 582787, tzinfo=utc)),
        ),
    ]
