# Generated by Django 3.0.2 on 2020-01-21 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20200114_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='voting_centre',
            field=models.CharField(default='Unity Primary School', max_length=50, verbose_name='Voting Centre'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 4, 54, 22, 975391, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 21, 4, 54, 22, 976390, tzinfo=utc)),
        ),
    ]
