# Generated by Django 3.0.2 on 2020-01-23 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_auto_20200122_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='uploaded_to_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 6, 20, 17, 300980, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sorted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 6, 20, 17, 301979, tzinfo=utc)),
        ),
    ]
