# Generated by Django 3.0.2 on 2020-01-10 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_number', models.PositiveIntegerField(unique=True, verbose_name='Identification Number')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=50)),
                ('phone_number', models.PositiveIntegerField(blank=True, default='0704893840', verbose_name='Phone Number')),
                ('dob', models.DateField(default=datetime.datetime(2020, 1, 10, 9, 15, 7, 126512, tzinfo=utc), verbose_name='Date of Birth')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
