# Generated by Django 3.0.2 on 2020-01-27 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 19, 0, 57, 170740, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
