# Generated by Django 3.0.2 on 2020-01-10 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 10, 10, 6, 17, 152535, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
