# Generated by Django 3.0.2 on 2020-01-28 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200127_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 11, 3, 10, 763283, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
