# Generated by Django 3.0.2 on 2020-01-29 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200128_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 17, 30, 33, 410273, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
