# Generated by Django 3.0.2 on 2020-01-11 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200110_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 17, 40, 33, 335214, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
