# Generated by Django 3.0.2 on 2020-01-11 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200111_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 17, 55, 3, 468986, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
