# Generated by Django 3.0.2 on 2020-01-30 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200129_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 6, 37, 55, 858945, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
