# Generated by Django 3.0.2 on 2020-01-14 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200111_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 9, 35, 33, 221855, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
