# Generated by Django 3.0.2 on 2020-01-31 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200130_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 10, 5, 36, 561133, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
