# Generated by Django 3.0.2 on 2020-02-13 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200131_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 4, 38, 54, 180585, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
