# Generated by Django 3.0.2 on 2020-01-23 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200122_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 6, 20, 17, 297981, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
