# Generated by Django 3.0.2 on 2020-01-23 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200123_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 10, 1, 43, 266619, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
