# Generated by Django 3.0.2 on 2020-01-26 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200126_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 15, 44, 7, 152482, tzinfo=utc), verbose_name='Date of Birth'),
        ),
    ]
